### ISSUE TITLE
Skapa om Adela_kia-vyn

### ISSUE THREAD

**Issue by wikolaw** [Mindcamp/SiS#48]
Lägg till  händelsedatum fr.o.m och t.o.m.

Använda tabellerna:
- Historik
- Historydetail

**Comment by wikolaw** [comment]
Ersätter #11 och #19

**Comment by wikolaw** [comment]
Tidsuppskattning 30-60h

**Comment by wikolaw** [comment]
Registreras avvikelse som en systemklass, ska det exkluderas från omfattningsberäkningen.

**Comment by PatrikRufelt** [comment]
HistoryPKnumber
